### ISSUE TITLE
Simpler fake-addon installation in Blender

### ISSUE THREAD

**Issue by daylanKifky** [douglaskastle/blender-fake-addon#3]
Hi!
first of all I would like to send you lots of :heart::heart::heart::heart: for sharing this. It was crucial to setup `pytest` on my own add-on.

while doing it I discovered a [little hidden utility function](https://docs.blender.org/api/current/bpy.utils.html#bpy.utils.refresh_script_paths) that allows you to effectively change  `script_directory` after setting it with python, without closing and opening Blender.

By using it you can enable the add-on for development purposes without zipping or copying any files. The `load_pytests.py` ends up like this:

```python
import pytest

import bpy

import sys
from os.path import join, abspath, dirname
dev_script_folder = join(dirname(abspath(__file__)), "../scripts")

addon = "fake_addon"


class SetupPlugin(object):
    def __init__(self, addon):
        self.addon = addon

    def pytest_configure(self, config):
        bpy.context.preferences.filepaths.script_directory = dev_script_folder
        bpy.utils.refresh_script_paths()
        bpy.ops.preferences.addon_enable(module=addon)
   
        config.cache.set("bpy_module", self.addon)

    def pytest_unconfigure(self):
        bpy.ops.preferences.addon_disable(module=self.addon)
        print("*** test run reporting finished ***")


try:
    exit_val = pytest.main(["test_cases"], plugins=[SetupPlugin(addon)])
except Exception as e:
    print(e)
    exit_val = 1
sys.exit(exit_val)
```
I'm pointing the `script_directory` to `"../scripts"` which should replicate the Blender's script folder structure, as stated [here](https://docs.blender.org/manual/en/latest/editors/preferences/file_paths.html#scripts-path):
```
scripts/addons/fake-addon/<__init__.py and addon-code here>
```

Hope this information helps improving your fake add-on!

**Comment by douglaskastle** [comment]
Interesting.  I think I see what you are suggesting, instead of copying the addon into a known/used script area (and deleting it at the end), you just get the scripts directory to point to a different directory. Is that correct? (all of it)

I am a bit mixed about this, as in my business we try and replicate the real world example as close as possible, because even though the two **_should_** be the same doesn't mean that they are. Windows is notorious for been flaky here in that regard.

What issues are you seeing with it the way it is currently implemented?

I'll see about providing it as a option as a first step, what do you think?

**Comment by douglaskastle** [comment]
Looking at your code, it ignores some of the zipping  I am doing under the hood.  If you have a single file addon, it will probably be fine.  

While my example is a single file, it is written to service multiple file, so even in the case of a single file addon, I install it as from a zip file.

Also in my example scripts has already been used up as a directory for my ... scripts.

I'll look in to this a bit more, but it is not a simple fold in, in its current form.

**Comment by daylanKifky** [comment]
Hi!
You are right about the practice of replicating the real world example as close as possible. I don't see any issue with the way it is implemented right now.
My suggestion was just targeted to avoid duplicating files, and polluting the real Blender `addons` folder in the unlikely case of an interrupted execution of the test suit. 

> While my example is a single file, it is written to service multiple file, so even in the case of a single file addon, I install it as from a zip file.

This strategy works with a python package as well as a single file

**Comment by douglaskastle** [comment]
Yes I agree with and have seen the interrupted execution problem, more when I was developing this tool.

I think I am zeroing in on a solution that takes care of the zip problem too.

**Comment by douglaskastle** [comment]
OK i have updated a fix to master where a local_directory is created and installed into and then deleted at the end.

It was probably not of interest to you, but the code required to run on <=2.79 was slightly different but I got that to work to.

**Comment by daylanKifky** [comment]
Great!
thanks for considering my suggestion!
